### ISSUE TITLE
sdl: document `command` and `args` usage

### ISSUE THREAD

**Issue by boz** [ovrclk/docs#117]
`args` is pretty unclear and surprising.  With the following SDL:

```yaml
  web:
    image: raviforbole/video-chat
    args:
      - "--VUE_APP_SOCKET_HOST=http://localhost"
      - "--VUE_APP_SOCKET_PORT=3000"
```
Pod creation fails with:

```
f7shd5o2mbfnpgmlij0af111naf7nif46al3l3gsvob7k   20s         Warning   Failed              pod/web-6bff748d8-lrgs9        Error: failed to start container "web": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"--VUE_APP_SOCKET_HOST=http://localhost\": stat --VUE_APP_SOCKET_HOST=http://localhost: no such file or directory": unknown
```

So it looks like the first element of `args:` should be the path to the executable.
